apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: dashd
    app: dashd
  name: dashd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: dashd
    spec:
      containers:
        - name: dashd
          image: kuberstack/dashd
          imagePullPolicy: Always
          ports:
            - containerPort: 443
              name: dashd-rpc
          volumeMounts:
            - mountPath: /srv/dashd
              name: dashd-pvc
            - mountPath: /etc/dashd
              name: dashd-conf
              readOnly: true
            - mountPath: /etc/dashd-ssl
              name: dashd-ssl
              readOnly: true
          resources:
            requests:
              cpu: 0.5
              memory: 512Mi
            limits:
              cpu: 4
              memory: 10000Mi
      volumes:
        - name: dashd-pvc
          persistentVolumeClaim:
            claimName: dashd-pvc
        - name: dashd-conf
          secret:
            secretName: dashd-conf
        - name: dashd-ssl
          secret:
            secretName: dashd-ssl
